spring:
  application:
    name: spaceapi
  datasource:
    # The jdbc url is: jdbc:h2:mem:schoolapidb
    url: jdbc:h2:mem:spaceapi;DB_CLOSE_DELAY=-1 # for In-memory database and jdbc:h2:file:[path/database-name] for disk-based database.
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true # The console url is: /h2-console
  ai:
    mistralai:
      api-key: Vr8GvfuIJZYn80Ie6JhS0j0cpRSsLjW7
      chat:
        options:
          model: mistral-small-latest
jwt:
  secret: "Kj83HwPQ9sZ2vL0fT5gR7nBcD4LmY8Qx"
  expiration: 3600000 # 1 hour
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8080
  forward-headers-strategy: framework
